apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/ryemorris/insights-ingress-go?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "true"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && target_branch
      == "security-compliance"
    pipelinesascode.tekton.dev/pipeline: https://github.com/ryemorris/konflux-pipelines/raw/main/pipelines/docker-build-oci-ta.yaml
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: test
    appstudio.openshift.io/component: insights-ingress
    pipelines.appstudio.openshift.io/type: build
  name: insights-ingress-on-pull-request
  namespace: rh-ee-rymorris-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/rh-ee-rymorris-tenant/insights-ingress:sc-{{body.pull_request.closed_at}}-{{revision}}
  - name: image-expires-after
    value: 5d
  - name: dockerfile
    value: ./Dockerfile
  pipelineRef:
    name: docker-build-oci-ta
  taskRunTemplate: {}
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
